import { Sana } from "./types";

export enum Cadeau_1 {
  Kappale_2 = "2. Bonjour",
  Kappale_3 = "3. Tu as quel âge ?",
  Kappale_4 = "4. Tu as des frères et sœurs ?",
  Kappale_5 = "5. Tu as un chien ?",
  Kappale_6 = "6. À l’école",
  Kappale_7 = "7. Les couleurs",
  Kappale_8 = "8. Qu'est-ce que fais",
  Kappale_9_1 = "9. C’est la fête - Joyeux Noël !",
}

export enum Cadeau_2 {
  Kappale_1 = "1. Vous êtes prêts ?",
}

export type Kappale = Cadeau_1 | Cadeau_2;

export const kappaleet: Record<Kappale, Array<Sana>> = {
  [Cadeau_1.Kappale_2]: [
    { fr: "bonjour", fi: "huomenta, hyvää päivää" },
    { fr: "les salutations", fi: "tervehdykset" },
    { fr: "salut", fi: "hei, moi" },
    { fr: "Ça va ?", fi: "Mitä kuuluu?" },
    { fr: "Ça va.", fi: "Kuuluu hyvää." },
    { fr: "Comment allez-vous?", fi: "Kuinka voitte?" },
    { fr: "madame", fi: "rouva" },
    { fr: "monsieur", fi: "herra" },
    { fr: "À plus tard !", fi: "Nähdään sitten (myöhemmin)!" },
    { fr: "À bientôt !", fi: "Nähdää pian!" },
    { fr: "Au revoir", fi: "näkemiin" },
    { fr: "la rentrée", fi: "koulun alku" },
    { fr: "je m'appelle", fi: "minun nimeni on" },
    { fr: "Et toi ?", fi: "Entä sinä?" },
    { fr: "moi", fi: "minä (itseä korostava sana)" },
    { fr: "je", fi: "minä" },
    { fr: "je suis", fi: "minä olen" },
    { fr: "Tu t'appelles comment ?", fi: "Mikä sinun nimesi on?" },
    { fr: "tu", fi: "sinä" },
    { fr: "tu es", fi: "sinä olet" },
    { fr: "voici", fi: "tässä on" },
    { fr: "la maitresse", fi: "opettaja" },
    { fr: "les enfants", fi: "lapset" },
    { fr: "Comment ça va ?", fi: "Mitä kuuluu?" },
    { fr: "bien", fi: "hyvää" },
    { fr: "merci", fi: "kiitos" },
    { fr: "la récré", fi: "välitunti" },
  ],
  [Cadeau_1.Kappale_3]: [
    { fi: "Kuinka vanha olet?", fr: "Tu as quel âge?" },
    { fi: "numerot", fr: "les nombres" },
    { fi: "Hyvää syntymäpäivää?", fr: "Bon anniversaire!" },
    { fi: "minun syntymäpäiväni", fr: "mos anniversaire" },
    { fi: "ole hyvä", fr: "tiens" },
    { fi: "lahja", fr: "un cardeau" },
    { fi: "kortti", fr: "une carte" },
    { fi: "kiitos", fr: "merci" },
    { fi: "mutta", fr: "mais" },
    { fi: "Olen 9-vuotias", fr: "J'ai neuf ans." },
    { fi: "vuosi", fr: "un an" },
    { fi: "oi, oi, ohoh", fr: "oh là là" },
    { fi: "kynttilä", fr: "une bougie" },
    { fi: "Katso!", fr: "Regarde!" },
    { fi: "kakku", fr: "un gâteau" },
    { fi: "nam", fr: "miam" },
    { fi: "Maistetaanko?", fr: "On goute?" },
    { fi: "omistaa; olla jonkun ikäinen", fr: "avoir" },
    { fi: "minulla on", fr: "j'ai" },
    { fi: "sinulla on", fr: "tu as" },
    { fi: "hänellä on (pojasta puhuttaessa)", fr: "il a" },
    { fi: "hänellä on (tytöstä puhuttaessa)", fr: "elle a" },
  ],
  [Cadeau_1.Kappale_4]: [
    { fi: "Onko sinulla sisaruksia?", fr: "Tu as des frères et sœurs?" },
    { fi: "minun perheeni", fr: "ma famille" },
    { fi: "perhevalokuvia", fr: "photos de famille" },
    { fi: "perhe", fr: "la famille" },
    { fi: "pikkusisko", fr: "un petite sœurs" },
    { fi: "pikkuveli", fr: "un petit frère" },
    { fi: "papukaija", fr: "un parroquet" },
    { fi: "lisko", fr: "un lézard" },
    { fi: "(poika) lapsi", fr: "fils" },
    { fi: "ainoa", fr: "unique" },
    { fi: "vanhempi sisarus", fr: "ainé" },
    { fi: "hauska", fr: "drôle" },
    { fi: "olla", fr: "être" },
    { fi: "minä olen", fr: "je suis" },
    { fi: "sinä olet", fr: "tu es" },
    { fi: "hän on (poika)", fr: "il est" },
    { fi: "hän on (tyttö)", fr: "tu es" },
  ],
  [Cadeau_1.Kappale_5]: [
    { fi: "Onko sinulla koira?", fr: "Tu as un chien?" },
    { fi: "eläimet", fr: "les animaux" },
    { fi: "minun eläimeni", fr: "mes animaux" },
    { fi: "piente lampaat", fr: "les petits moutons" },
    { fi: "pieni", fr: "petit, petite" },
    { fi: "Ei", fr: "Non." },
    { fi: "Minulla ei ole...", fr: "Je n'ai pas de..." },
    { fi: "Katsokaa!", fr: "Regardez!" },
    { fi: "lampaita", fr: "des moutons" },
    { fi: "ja", fr: "et" },
    { fi: "lehmiä", fr: "des vaches" },
    { fi: "Joo. Kyllä.", fr: "Oui!" },
    { fi: "koiria", fr: "des chiens" },
    { fi: "kissoja", fr: "des chats" },
    { fi: "Oi!", fr: "Oh!" },
    { fi: "Ne ovat niin söpöjä.", fr: "Ils sont tellements jolis." },
    { fi: "ne ovat", fr: "ils sont" },
    { fi: "niin", fr: "tellement" },
    { fi: "sievä, söpö", fr: "joli, jolie" },
    { fi: "Hän on nimeltään", fr: "Il s'appelle" },
  ],
  [Cadeau_1.Kappale_6]: [
    { fi: "koulussa", fr: "à l'école" },
    { fi: "koulu", fr: "une école" },
    { fi: "koulutarvikkeet", fr: "le matèriel scolaire" },
    { fi: "luokassa", fr: "dans la trousse" },
    { fi: "luokassa", fr: "en classe" },
    { fi: "luokka", fr: "une classe" },
    { fi: "kertaa", fr: "fois" },
    { fi: "on yhteensä", fr: "font" },
    { fi: "helppo", fr: "facile" },
    { fi: "todella hyvä", fr: "très bien" },
    { fi: "lapsi", fr: "un enfant" },
    { fi: "matematiikan tunti", fr: "un cours de math" },
    { fi: "mutta", fr: "mais" },
    { fi: "miksi", fr: "pourquoi" },
    { fi: "pahoillaan", fr: "désolé, désolée" },
    { fi: "ranskan vihko", fr: "un cahier de français" },
    { fi: "oho, hups", fr: "oups" },
    { fi: "antaa lainaksi", fr: "prêter (I)" },
    { fi: "Lainaatko minulle?", fr: "Tu me prêtes?" },
    { fi: "tietysti", fr: "bien sûr" },
    { fi: "ole hyvä (annettaessa)", fr: "voilà" },
    { fi: "kuinka paljon", fr: "combien de" },
    { fi: "en tiedä", fr: "je ne sais pas" },
    { fi: "viisitoista", fr: "quinze" },
    { fi: "lasketaan ne", fr: "on les compte" },
  ],
  [Cadeau_1.Kappale_7]: [
    { fi: "värit", fr: "les couleurs" },
    { fi: "Minkä värinen se on?", fr: "C'est de quelle couleur?" },
    { fi: "eläintaulu", fr: "chanson des animaux" },
    { fi: "Missä on minun kumini?", fr: "Où est ma gomme?" },
    { fi: "missä", fr: "où" },
    { fi: "minun", fr: "mon, ma" },
    { fi: "anteeksi", fr: "pardon" },
    { fi: "Ei haittaa", fr: "Ce n'est pas grave." },
    { fi: "sinun", fr: "ton, ta" },
    { fi: "Se on totta", fr: "C'est vrai." },
    {
      fi: "Minkä värinen sinun kuulakärkikynäsi on?",
      fr: "Ton stylo est de quelle couleur?",
    },
    { fi: "myös", fr: "aussi" },
    { fi: "nyt", fr: "maintenant" },
    { fi: "suloinen", fr: "mignon, mignonne" },
    { fi: "tuolla on", fr: "il y a" },
    { fi: "paljon", fr: "beaucoup de" },
    { fi: "ilmapallo, pallo", fr: "un ballon" },
    { fi: "Mennäänkö sinne?", fr: "On y va?" },
    { fi: "nopeasti", fr: "vite" },
  ],
  [Cadeau_1.Kappale_8]: [
    { fr: "le temps libre", fi: "vapaa-aika" },
    { fr: "les loisirs", fi: "harrastukset" },
    { fr: "Action!", fi: "Toimintaa!" },
    { fr: "Qu'est-ce que tu fais?", fi: "Mitä sinä teet?" },
    { fr: "dans un park", fi: "puistossa" },
    { fr: "un parc", fi: "puisto" },
    { fr: "un e tablette", fi: "tablettitietokone" },
    { fr: "chouette", fi: "kiva" },
    { fr: "gagner", fi: "kiva" },
    { fr: "trop", fi: "liian,liikaa" },
    { fr: "difficile", fi: "vaikea" },
    { fr: "avec moi", fi: "kanssani" },
    { fr: "fatigué, fatiguée", fi: "väynyt" },
    { fr: "là-bas", fi: "tuolla" },
    { fr: "jouer au rugby", fi: "pelata rugbyä" },
    { fr: "dans une équipe", fi: "joukkueessa" },
    { fr: "une équipe", fi: "joukkue" },
    { fr: "cool", fi: "tosi hieno" },
    { fr: "bien", fi: "hyvin" },
    { fr: "pas mal", fi: "ei hullummin" },
    { fr: "mal", fi: "huonosti" },
    { fr: "rigoler", fi: "hassutella, pitää hauskaa" },
    { fr: "faire", fi: "tehdä" },
    { fr: "je fais", fi: "minä teen" },
    { fr: "tu fais ", fi: "sinä teet" },
    { fr: "il fais", fi: "hän tekee" },
    { fr: "elle fais", fi: "hän tekee" },
    { fr: "une chanson", fi: "laulu" },
  ],
  [Cadeau_1.Kappale_9_1]: [
    { fr: "Joyeux Noël !", fi: "Iloista joulua!" },
    { fr: "Noël", fi: "joulu" },
    { fr: "le sapin", fi: "kuusi" },
    { fr: "la guirlande", fi: "koristenauha" },
    { fr: "la boule", fi: "(joulu)pallo" },
    { fr: "l'étoile", fi: "tähti" },
    { fr: "l'ange", fi: "enkeli" },
    { fr: "la bougie", fi: "kynttilä" },
    { fr: "la crèche de Noël", fi: "jouluseimi" },
    { fr: "le lutin", fi: "tonttu" },
    { fr: "le renne", fi: "poro" },
    { fr: "le père Noël", fi: "joulupukki" },
    { fr: "le traineau", fi: "reki" },
    { fr: "la fête de Noël", fi: "joulujuhla" },
    { fr: "beau, belle", fi: "kaunis" },
    { fr: "on aime", fi: "tykätään" },
    { fr: "la nouvelle année", fi: "uusi vuosi" },
    { fr: "la buche de Noël", fi: "jouluhalko" },
    { fr: "sur le sapin", fi: "kuuseen, kuusessa" },
  ],
  [Cadeau_2.Kappale_1]: [
    { fr: "vous êtes", fi: "te olette" },
    { fr: "prêt, prête", fi: "valmis" },
    { fr: "C'est moi !", fi: "Tässäpä minä!" },
    { fr: "mon, ma", fi: "minun" },
    { fr: "un âge", fi: "ikä" },
    { fr: "un professeur", fi: "opettaja (mies)" },
    { fr: "une professeure", fi: "opettaja (nainen)" },
    { fr: "la rentrèe", fi: "koulun alku" },
    { fr: "un copain, une copine", fi: "kaveri" },
    { fr: "encore", fi: "vielä" },
    { fr: "les autres", fi: "muut" },
    { fr: "un départ", fi: "lähtö" },
    { fr: "un crayon", fi: "lyijykynä" },
    { fr: "danser", fi: "tanssia" },
    { fr: "vingt", fi: "kaksikymmentä" },
    { fr: "une étoile", fi: "tähti" },
    { fr: "dessiner (I)", fi: "piirtää" },
    { fr: "il", fi: "hän (pojasta)" },
    { fr: "un chat", fi: "kissa" },
    { fr: "douze", fi: "kaksitoista" },
    { fr: "un sac à dos", fi: "reppo" },
    { fr: "un lézard", fi: "lisko" },
    { fr: "manger", fi: "syödä" },
    { fr: "dix-huit", fi: "kahdeksantoista" },
    { fr: "un chien", fi: "koira" },
    { fr: "seize", fi: "kuusitoista" },
    { fr: "elle", fi: "hän (tytöstä)" },
    { fr: "une gomme", fi: "kumi" },
    { fr: "une arrivée", fi: "maali" },
  ],
};
